### ISSUE TITLE
Initial project meeting

### ISSUE THREAD

**Issue by ShwangShwing** [ShwangShwing/maistore-maistore#1]
Agenda:

1. Discuss page structure
2. Discuss database structure
3. Discuss project file structure
4. Create and split initial tasks

**Comment by stefanmanev** [comment]
We will be discussing all things today at 11:00 am.

**Comment by ShwangShwing** [comment]
Report:
1. Page structure was decided. I will upload pictures with the individual pages and upload them
2. Database structure was decided
3. The project file structure was NOT decided. It will be decided dynamically during development.
4. The tasks were decided to be roughly one page - one task. 
Please, since we will be working using git flow, for each task a new feature branch must be created from the development branch (I will create this).
